[cerebrium.deployment]
name = "socketiopeer"
python_version = "3.12"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 2.0
memory = 12.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0

[cerebrium.runtime.custom]
port = 5000
entrypoint = ["gunicorn", "main:app"]
healthcheck_endpoint = "/health"

[cerebrium.dependencies.pip]
flask = 'latest'
flask-socketio = "latest"
gunicorn = "latest"